version: '3.8'

services:


  rentacardbdev: 
    container_name: rentacardbdev
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345